version: '3'

services:
  web:
    build: .
    env_file: ./.env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && daphne --bind 0.0.0.0:8002 great_chat.asgi:application"
    container_name: great_chat
    volumes:
      - .:/great_chat
    ports:
      - "8002:8002"
    restart: unless-stopped