version: '3'

services:
  web:
    build: .
    env_file: ./.env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8016 great_chat.wsgi"
    image: great_chat
    container_name: great_chat
    volumes:
      - .:/great_chat
    ports:
      - "8016:8016"
    restart: unless-stopped