apiVersion: v1
kind: Service
metadata:
  name: great-chat-service
spec:
  selector:
    app: great-chat
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 32002
  type: NodePort