apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: great-chat
  namespace: arpansahu-one-namespace
  labels:
    app: great-chat
    app.kubernetes.io/instance: great-chat
    app.kubernetes.io/name: great-chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn